deployment:
  svc: true
  bff: true
  ui: true

product:
  info:
    data:
      description: "OneCX Tenant"
      imageUrl: ""
      iconName: "lock"
      displayName: "OneCX Tenant"
      basePath: "/tenant"
      
